scan_timeout = 150
format = """
[](#14FFD1)\
$os\
$username\
[](bg:#2BE28A fg:#14FFD1)\
$directory\
[](fg:#2BE28A bg:#FFB66E)\
$git_branch\
$git_status\
[](fg:#FFB66E bg:#66E0FF)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#66E0FF bg:#2BE28A)\
$docker_context\
[](fg:#2BE28A bg:#14FFD1)\
$time\
[ ](fg:#14FFD1)\
"""

[username]
show_always = true
style_user = "bg:#14FFD1 fg:#000000"
style_root = "bg:#14FFD1 fg:#000000"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#14FFD1 fg:#000000"
disabled = true

[directory]
style = "bg:#2BE28A fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#2BE28A fg:#000000"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FFB66E fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FFB66E fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#66E0FF fg:#000000"
disabled = true
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
disabled = true
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
disabled = true
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
disabled = true
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
disabled = true
symbol = "󰆥 "
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
disabled = true
style = "bg:#66E0FF fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#14FFD1 fg:#000000"
format = '[ 󰣇 $time]($style)'

